### ISSUE TITLE
Things todo before initial launch

### ISSUE THREAD

**Issue by djds23** [djds23/regularly-react#10]
- [x] make the show/hide button more obvious
- [x] better group album selection/selector information
- [x] make timestamp more readable
